name: C++ CI

on: [push, pull_request, workflow_dispatch]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  DEBIAN_FRONTEND: noninteractive

jobs:
  build_and_test:
    runs-on: self-hosted
    container: ubuntu:20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      working-directory: docker
      run: ./install.sh

    - name: Configure CMake
      working-directory: ./challenge_01_isometries
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ./challenge_01_isometries
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ./challenge_01_isometries/build
      run: ctest -C ${{env.BUILD_TYPE}}